### ISSUE TITLE
Thrift dependancy

### ISSUE THREAD

**Issue by rusher81572** [tomitakazutaka/fluent-plugin-cassandra#1]
Hello, can you please help me figure out how to get this plugin working? I am getting the following error when starting fluent
```
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'thrift_client' (~> 0.7.0) - did find: [thrift_client-0.9.3] (Gem::LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all', execute `gem env` for more information
	from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /var/lib/gems/2.3.0/gems/cassandra-0.12.1/lib/cassandra.rb:2:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-cassandra-0.0.2/lib/fluent/plugin/out_cassandra.rb:15:in `initialize'
```

**Comment by tomitakazutaka** [comment]
I'm Sorry, I don't update at present. 
When you need, I think to update to the latest version within 2 weeks.

**Comment by rusher81572** [comment]
Thank you. can you please explain how the mapping works?

My table is:
```
CREATE TABLE tweets (Date text ,UserName text, Tweet text, URL text, PRIMARY KEY(Date, Username));
```

My node.js app sends data to fluent like this:
```
  var message = JSON.stringify({
        'date': event.created_at,
        'username': event.user.screen_name,
        'tweet': event.text,
        'url:': 'https://twitter.com/' + event.user.screen_name + '/status/' + event.id_str,
      });
```

Will it automatically do the mapping?

**Comment by tomitakazutaka** [comment]
That's right.
I'm making it for that aim.
